[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asyncmy>=0.2.14",
    "fastapi>=0.141.1",
    "loguru>=0.7.3",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "redis>=8.1.0",
    "sqlalchemy[asyncio]>=2.0.52",
    "uvicorn>=0.52.4",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "ruff>=0.16.4",
    "ty>=0.0.73",
]

[tool.ruff]
line-length = 100
